// Global configuration.
// Override apiUrl and apiKey per-page via <meta> tags (no JS editing needed):
//   <meta name="api-url" content="https://api.yahyaartisan.shop/api">
//   <meta name="api-key" content="YOUR_KEY_HERE">
const _metaContent = name => document.querySelector(`meta[name="${name}"]`)?.content || '';

window.CONFIG = {
    apiUrl:   _metaContent('api-url')  || 'http://localhost:8001/api',
    apiKey:   _metaContent('api-key')  || 'f99c4435c23a220b7789680ff0a65a723059ab082920c6e66e8ef49335b4deee',
    waNumber: _metaContent('wa-number')|| '213775108618',

    wilayas: [
        { code: 28, name: 'المسيلة',         zone: 1, shipping: 400 },
        { code: 17, name: 'الجلفة',           zone: 1, shipping: 400 },
        { code: 5,  name: 'باتنة',            zone: 1, shipping: 400 },
        { code: 7,  name: 'بسكرة',            zone: 1, shipping: 400 },
        { code: 34, name: 'برج بوعريريج',     zone: 1, shipping: 400 },
        { code: 3,  name: 'الأغواط',          zone: 1, shipping: 400 },
        { code: 51, name: 'أولاد جلال',       zone: 1, shipping: 400 },
        { code: 16, name: 'الجزائر',          zone: 2, shipping: 600 },
        { code: 9,  name: 'البليدة',          zone: 2, shipping: 600 },
        { code: 19, name: 'سطيف',             zone: 2, shipping: 600 },
        { code: 25, name: 'قسنطينة',          zone: 2, shipping: 600 },
        { code: 6,  name: 'بجاية',            zone: 2, shipping: 600 },
        { code: 15, name: 'تيزي وزو',         zone: 2, shipping: 600 },
        { code: 26, name: 'المدية',           zone: 2, shipping: 600 },
        { code: 35, name: 'بومرداس',          zone: 2, shipping: 600 },
        { code: 10, name: 'البويرة',          zone: 2, shipping: 600 },
        { code: 43, name: 'ميلة',             zone: 2, shipping: 600 },
        { code: 4,  name: 'أم البواقي',       zone: 2, shipping: 600 },
        { code: 40, name: 'خنشلة',            zone: 2, shipping: 600 },
        { code: 12, name: 'تبسة',             zone: 2, shipping: 600 },
        { code: 18, name: 'جيجل',             zone: 2, shipping: 600 },
        { code: 36, name: 'الطارف',           zone: 2, shipping: 600 },
        { code: 21, name: 'سكيكدة',           zone: 2, shipping: 600 },
        { code: 44, name: 'عين الدفلة',       zone: 2, shipping: 600 },
        { code: 42, name: 'تيبازة',           zone: 2, shipping: 600 },
        { code: 2,  name: 'الشلف',            zone: 2, shipping: 600 },
        { code: 27, name: 'مستغانم',          zone: 2, shipping: 600 },
        { code: 38, name: 'تيسمسيلت',         zone: 2, shipping: 600 },
        { code: 14, name: 'تيارت',            zone: 2, shipping: 600 },
        { code: 20, name: 'سعيدة',            zone: 2, shipping: 600 },
        { code: 29, name: 'معسكر',            zone: 2, shipping: 600 },
        { code: 47, name: 'غرداية',           zone: 2, shipping: 600 },
        { code: 39, name: 'الوادي',           zone: 2, shipping: 600 },
        { code: 30, name: 'ورقلة',            zone: 2, shipping: 600 },
        { code: 55, name: 'توقرت',            zone: 2, shipping: 600 },
        { code: 57, name: 'المغير',           zone: 2, shipping: 600 },
        { code: 58, name: 'المنيعة',          zone: 2, shipping: 600 },
        { code: 31, name: 'وهران',            zone: 3, shipping: 800 },
        { code: 13, name: 'تلمسان',           zone: 3, shipping: 800 },
        { code: 22, name: 'سيدي بلعباس',      zone: 3, shipping: 800 },
        { code: 46, name: 'عين تموشنت',       zone: 3, shipping: 800 },
        { code: 48, name: 'غليزان',           zone: 3, shipping: 800 },
        { code: 41, name: 'سوق أهراس',        zone: 3, shipping: 800 },
        { code: 23, name: 'عنابة',            zone: 3, shipping: 800 },
        { code: 24, name: 'قالمة',            zone: 3, shipping: 800 },
        { code: 32, name: 'البيض',            zone: 3, shipping: 800 },
        { code: 45, name: 'النعامة',          zone: 3, shipping: 800 },
        { code: 8,  name: 'بشار',             zone: 3, shipping: 800 },
        { code: 1,  name: 'أدرار',            zone: 3, shipping: 800 },
        { code: 37, name: 'تندوف',            zone: 3, shipping: 800 },
        { code: 11, name: 'تمنراست',          zone: 3, shipping: 800 },
        { code: 33, name: 'إليزي',            zone: 3, shipping: 800 },
        { code: 49, name: 'تيميمون',          zone: 3, shipping: 800 },
        { code: 50, name: 'برج باجي مختار',   zone: 3, shipping: 800 },
        { code: 52, name: 'بني عباس',         zone: 3, shipping: 800 },
        { code: 53, name: 'عين صالح',         zone: 3, shipping: 800 },
        { code: 54, name: 'عين قزام',         zone: 3, shipping: 800 },
        { code: 56, name: 'جانت',             zone: 3, shipping: 800 },
    ],
};
